### ISSUE TITLE
How to process the scannet200 data?

### ISSUE THREAD

**Issue by yichaoshen-MS** [RozDavid/LanguageGroundedSemseg#12]
Hello,
I cannot find the python script (scannet_long.py, scannet200_insseg.py) to process the original scannet data ?
Where can I get the script ?

**Comment by RozDavid** [comment]
[Here](https://github.com/RozDavid/LanguageGroundedSemseg/blob/master/lib/datasets/preprocessing/scannet_long.py) and [here](https://github.com/RozDavid/LanguageGroundedSemseg/blob/master/lib/datasets/preprocessing/scannet200_insseg.py)

**Comment by yichaoshen-MS** [comment]
> [Here](https://github.com/RozDavid/LanguageGroundedSemseg/blob/master/lib/datasets/preprocessing/scannet_long.py) and [here](https://github.com/RozDavid/LanguageGroundedSemseg/blob/master/lib/datasets/preprocessing/scannet200_insseg.py)

Which the difference the process script of scannet200 in this Repostitory(LanguageGroundedSemseg) and the Repostitory（scannet :https://github.com/ScanNet/ScanNet/blob/master/BenchmarkScripts/ScanNet200/preprocess_scannet200.py）?

**Comment by RozDavid** [comment]
Basically no difference, in this repo we added a couple extra functionalities, e.g. the limited annotation preprocessing. 
You are free to choose though according to your preference.
