### ISSUE TITLE
What the True format of test_output of instance segmentation batchmark?

### ISSUE THREAD

**Issue by yichaoshen-MS** [RozDavid/LanguageGroundedSemseg#13]
Hi,If I would like to upload the result of segmentation, what is the True format ?

**Comment by RozDavid** [comment]
For that please follow the submission format for the original scannet benchmark, but with the raw ScanNet200 labels. Please refer to the documentation for more details [here](https://kaldir.vc.in.tum.de/scannet_benchmark/documentation#label-set-scannet200).

**Comment by RozDavid** [comment]
Colsing the issue for now as it looks inactive/I might have answered it with my previous comment.
