### ISSUE TITLE
How to do the instance augmentation?

### ISSUE THREAD

**Issue by MurphyJUAN** [RozDavid/LanguageGroundedSemseg#16]
Hi, so many thanks for your wonderful work!
When I want to do the instance augmentation mentioned in paper section 3.2, I set the --instance_augmentation to be 'raw' in config.py and use focal loss.
However, I get the following error when I run the code:
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/20442086/209699155-1d685fa2-3748-4ef2-95f4-0ae27601637f.png">
It seems instance augmentation would change the shape of the label.
How can I fix it?
Thanks.

**Comment by RozDavid** [comment]
Hey again, 

The flag that you are looking for for tail instance sampling is `sample_tail_instances`, where you should also set the path where your instance meshes are saved. Please check the implementation for more details [here](https://github.com/RozDavid/LanguageGroundedSemseg/blob/3af87e933064414e7801dba82932b9f1a3440ae0/lib/datasets/scannet.py#L143). 

What you set to True is an other flag where we tested language-based augmentations with object properties and adjectives, but didn't follow up for this paper. You can leave that unchanged or experiment with it if it could be helpful for your use case. 

Hope this helps, 
David
