### ISSUE TITLE
Can I fetch individual objects from segmented point cloud?

### ISSUE THREAD

**Issue by ayaan-mphasis** [RozDavid/LanguageGroundedSemseg#24]

**Comment by RozDavid** [comment]
That's basically the task of instance segmentation. You can run our pretraining method and followed by the instance segmentation downstream task. After that you could filter for instance id, which will give you all the associated points for an individual object. 

Hope this helps!

**Comment by RozDavid** [comment]
Closing this issue as seems to be answered - feel free to reopen if you have any more questions.
