### ISSUE TITLE
Acquiring the updated scannetv2-labels.combined.tsv

### ISSUE THREAD

**Issue by LiyaoTang** [RozDavid/LanguageGroundedSemseg#5]
Hi David,

Thanks for your data set release, it's amazing. However, when I tried to acquire the updated tsv file for ScanNet200, I simply re-run the download script with `--label_map` option and found the downloaded tsv file is the same as the one I already have.

For your convenience, the md5sum of the newly downloaded tsv file and the old file I have are the same, which is `ea58dc6921c6a51569e3d3cf77fec182`.

So, do I need to get the new download script to get the new tsv file? i.e., to fill another TOS form?

Best,
Liyao Tang

**Comment by LiyaoTang** [comment]
Hi @RozDavid,

Thanks for your prompt reply.

I’ve also considered the case that I have already got the new one. However, the thing that confuse me is that, it seems several classes in the mapping appears to have the same nyu40id id.

Or, I need to use the id from another column, probably the "id" I guess?

Best,
Liyao

**Comment by RozDavid** [comment]
Hi, 

You are right, we use the _id_ instead of _nyu_id_ to avoid limitation to the predefined categories. 
You can also look into the preprocessing code [here](https://github.com/RozDavid/LanguageGroundedSemseg/blob/880b417bf7510e185dbf37c062cba9c61282edb4/lib/datasets/preprocessing/utils.py#L11) that might help undestanding the table. 

Regards, 
David

**Comment by LiyaoTang** [comment]
Hi,

Thank you for the link, that's much clearer.

However, as I'm reading through the ScanNet200 instruction from the repo of ScanNet, I find this confusing
https://github.com/ScanNet/ScanNet/blob/84178a87713b517dfdb05e0b7056493a627c24ff/BenchmarkScripts/ScanNet200/scannet200_splits.py#L10. Dose it mean the benchmark would NOT include those labels (the VALID_CLASS_IDS_200_TRAIN_ONLY) for evaluation on test set?

Thanks again.

Best,
Liyao

**Comment by RozDavid** [comment]
Hi Liyao, 

So, this set of categories only corresponding to the differences between train and val sets. 
We didn't make it public which categories might or might not be present on the test set, so you are free to ignore that. 

Regards, 
David

**Comment by LiyaoTang** [comment]
Ok, I see. Now everything is clear.

Thank you very much!

Cheers,
Liyao
